// test/dynamic-config-resync-merge.test.ts
// Phase 0 step 3 of docs/plans/2026-10-05-task-type-balancing.md — the
// sim/live divergence. Live routing runs on router-config.dynamic.json, and
// regeneration spreads the PREVIOUS dynamic file, so a top-level key added
// to the shipped router-config.json after the file first existed never
// reaches live routing. best_quality_window (ADR-0023) was such a key: the
// window was never active live, `best` ranked by pure score, and opus beat
// sonnet in strategic/planning (router log: opus 463 vs sonnet-5-5 55).
//
// Two guards:
//   1. every top-level key of the shipped config is either re-synced
//      wholesale, merged per entry, or regenerated by the scan — a new key
//      fails here until it is classified;
//   2. the per-entry merge keys (providers, model_metrics, gdpval_builtin)
//      carry static entries into the live config (static wins per entry)
//      while keeping scan-added entries.

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  DYNAMIC_CONFIG_RESYNC_KEYS,
  DYNAMIC_CONFIG_MERGE_KEYS,
  resyncDynamicFromStatic,
} from '../src/dynamic-config.ts';
import type { Config } from '../src/types.ts';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

describe('every shipped top-level config key reaches the live config', () => {
  it('is re-synced, merged, or scan-regenerated (model_groups)', () => {
    const shipped = JSON.parse(fs.readFileSync(path.join(repo, 'router-config.json'), 'utf-8'));
    const handled = new Set<string>([...DYNAMIC_CONFIG_RESYNC_KEYS, ...DYNAMIC_CONFIG_MERGE_KEYS, 'model_groups']);
    const unhandled = Object.keys(shipped).filter((k) => !handled.has(k));
    expect(unhandled).toEqual([]);
  });
});

describe('resyncDynamicFromStatic', () => {
  const staticCfg = {
    best_quality_window: 0.05,
    providers: {
      openrouter: { billing: 'pay_per_token', free_models: ['openrouter/new:free'] },
      'claude-bridge': { cost_per_m: 0.000001 },
    },
    model_metrics: {
      'claude-bridge/claude-sonnet-5-5': { cost_per_m: 1.5e-6 },
    },
    gdpval_builtin: { 'model-x': 1200 },
    model_groups: {},
  } as unknown as Config;

  const staleDynamic = () => ({
    _dynamic: { generated_at: '2026-10-05T11:00:00.000Z' },
    model_groups: { tactical: { method: 'best', models: ['a/b'] } },
    providers: {
      openrouter: { billing: 'pay_per_token', free_models: ['openrouter/old:free'] },
      // Scan-added entry (unknown provider auto-registered as subscription).
      'claude-bridge': { billing: 'subscription' },
      tactical: { billing: 'subscription' },
    },
    model_metrics: {
      'claude-bridge/claude-opus-5-5': { cost_per_m: 1.5e-6 },
    },
    gdpval_builtin: { 'model-x': 900, 'model-y': 800 },
  }) as unknown as Config;

  it('copies re-sync keys wholesale (the missing best_quality_window)', () => {
    const dyn = staleDynamic();
    resyncDynamicFromStatic(dyn, staticCfg);
    expect(dyn.best_quality_window).toBe(0.05);
  });

  it('merges providers per entry: static fields win, scan-added entries and fields stay', () => {
    const dyn = staleDynamic();
    resyncDynamicFromStatic(dyn, staticCfg);
    expect(dyn.providers!.openrouter.free_models).toEqual(['openrouter/new:free']);
    expect(dyn.providers!['claude-bridge']).toEqual({ billing: 'subscription', cost_per_m: 0.000001 });
    expect(dyn.providers!.tactical).toEqual({ billing: 'subscription' });
  });

  it('merges model_metrics per ref and gdpval_builtin per slug (static wins)', () => {
    const dyn = staleDynamic();
    resyncDynamicFromStatic(dyn, staticCfg);
    expect(dyn.model_metrics['claude-bridge/claude-sonnet-5-5']).toEqual({ cost_per_m: 1.5e-6 });
    expect(dyn.model_metrics['claude-bridge/claude-opus-5-5']).toEqual({ cost_per_m: 1.5e-6 });
    expect(dyn.gdpval_builtin).toEqual({ 'model-x': 1200, 'model-y': 800 });
  });

  it('leaves the scan-regenerated model_groups alone', () => {
    const dyn = staleDynamic();
    resyncDynamicFromStatic(dyn, staticCfg);
    expect(dyn.model_groups).toEqual({ tactical: { method: 'best', models: ['a/b'] } });
  });
});
