/**
 * Regression test for the "sticky model" bug (introduced in commit 72ace9e,
 * shipped in v1.2.0): driveStream() used to call pi.setModel(realModel) after
 * picking a candidate. That swaps the *session's* active model away from the
 * virtual group model, which fires model_select and permanently clears
 * activeGroup — after the first request, group routing silently stops and
 * every subsequent turn goes straight to whatever model won the first race.
 *
 * This test drives the real extension's groupStream() twice with two
 * available candidate models and asserts:
 *   1. pi.setModel() is never called by the router itself.
 *   2. Each call re-resolves candidates from the live model registry (i.e.
 *      routing keeps working on the second turn, not just the first).
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import type { AssistantMessageEvent } from '@earendil-works/pi-ai';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// router-config.dynamic.json is a gitignored, machine-local cache generated by
// `/router scan`. Its group->models pins reflect whatever was configured on
// this specific machine at scan time (e.g. only mistral if that's all that had
// keys) and go stale as providers are added/removed — exactly the kind of
// baked-in single-provider list that can make a group look "stuck" on one
// model regardless of the sticky-model bug under test here. Move it aside for
// the duration of this test so the test exercises real dynamic discovery
// (allDiscoveredRefs()) instead of whatever happens to be cached locally.
const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dynamicConfigPath = path.join(repoRoot, 'router-config.dynamic.json');
const dynamicConfigBackupPath = `${dynamicConfigPath}.regression-test-bak`;

async function drainStream(stream: AsyncIterable<AssistantMessageEvent>) {
  const events: AssistantMessageEvent[] = [];
  for await (const ev of stream) events.push(ev);
  return events;
}

describe('Sticky model regression (driveStream must never call pi.setModel)', () => {
  let mod: typeof import('../index.ts');
  let defaultExport: any;

  beforeEach(async () => {
    if (fs.existsSync(dynamicConfigPath)) {
      fs.renameSync(dynamicConfigPath, dynamicConfigBackupPath);
    }
    vi.resetModules();
    mod = await import('../index.ts');
    defaultExport = mod.default;
  });

  afterEach(() => {
    if (fs.existsSync(dynamicConfigBackupPath)) {
      fs.renameSync(dynamicConfigBackupPath, dynamicConfigPath);
    }
  });

  it('routes to a different candidate on each call without ever swapping the session model', async () => {
    const onHandlers: Record<string, (ev: any, ctx: any) => any> = {};
    const setModel = vi.fn(async () => true);

    const pi: any = {
      registerTool: vi.fn(),
      registerCommand: vi.fn(),
      registerProvider: vi.fn(),
      setModel,
      on: vi.fn((event: string, handler: any) => {
        onHandlers[event] = handler;
      }),
    };

    defaultExport(pi);

    // Two fake "real" candidate models on providers the router does not
    // manage itself (not in PROVIDER_MAP), so no apiKey is required — mirrors
    // how an extension-registered provider (e.g. claude-bridge) looks to the
    // router. Both use gdpval-mapped ids so the "standard" group's
    // min_gdpval threshold accepts them.
    const fakeModels: Record<string, any> = {
      'fake-provider-a/claude-sonnet-4-6': {
        provider: 'fake-provider-a',
        id: 'claude-sonnet-4-6',
        api: 'fake-api',
      },
      'fake-provider-b/claude-opus-4-6': {
        provider: 'fake-provider-b',
        id: 'claude-opus-4-6',
        api: 'fake-api',
      },
    };

    function makeStream(providerId: string) {
      return (async function* () {
        yield { type: 'text_delta', text: `hi from ${providerId}` };
        yield { type: 'done' };
      })();
    }

    const modelRegistry = {
      getAvailable: () => Object.values(fakeModels),
      find: (provider: string, id: string) => fakeModels[`${provider}/${id}`] ?? null,
      getApiKeyForProvider: async () => null,
      runtime: {
        streamSimple: (model: any) => makeStream(model.provider),
      },
    };

    const ctx: any = {
      modelRegistry,
      cwd: process.cwd(),
      ui: { setFooter: vi.fn() },
    };
    await onHandlers['session_start']?.({}, ctx);

    const groupModel = { provider: 'standard', id: 'standard' };
    const context: any = { messages: [{ role: 'user', content: 'hello' }] };

    for (let turn = 0; turn < 2; turn++) {
      const stream = defaultExport.groupStream(groupModel, context, {});
      const events = await drainStream(stream);
      const textEvents = events.filter((e: any) => e.type === 'text_delta');
      expect(textEvents.length).toBeGreaterThan(0);
    }

    // The router must never mutate the session's active model — that is
    // exactly the bug that made group routing stop working after turn 1.
    expect(setModel).not.toHaveBeenCalled();
  });
});
