/**
 * Regression test for the "sticky model" bug (introduced in commit 72ace9e,
 * shipped in v1.2.0): driveStream() used to call pi.setModel(realModel) after
 * picking a candidate. That swaps the *session's* active model away from the
 * virtual group model, which fires model_select and permanently clears
 * activeGroup — after the first request, group routing silently stops and
 * every subsequent turn goes straight to whatever model won the first race.
 *
 * This test drives the real extension's groupStream() twice with two
 * available candidate models and asserts:
 *   1. pi.setModel() is never called by the router itself.
 *   2. Each call re-resolves candidates from the live model registry (i.e.
 *      routing keeps working on the second turn, not just the first).
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import type { AssistantMessageEvent } from '@earendil-works/pi-ai';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { acquireRouterStateLock, releaseRouterStateLock, writeNoOpScanCache, removeNoOpScanCache } from './helpers/router-state-lock.ts';

// router-config.dynamic.json and .cache/scan-cache.json are gitignored,
// machine-local caches generated by `/router scan`. Both are resolved from
// extDir (index.ts's own directory, i.e. the repo root) rather than cwd, so
// they're shared global state across every test file in the suite regardless
// of any cwd mocking — a test file that doesn't move them aside is exposed to
// whatever another, concurrently-running test file leaves in them. In
// particular, scan-cache.json can carry real gdpval scores from a prior
// `/router scan` on this machine; on a fresh CI checkout it doesn't exist yet
// and the group resolution this test depends on becomes order-dependent on
// whichever other test happens to populate it first (see cooldown-collapse
// and runtime-overflow-detection tests, which isolate the same two files).
// Move both aside for the duration of this test so it exercises real dynamic
// discovery (allDiscoveredRefs()) purely from the mocked modelRegistry,
// deterministically.
const repoRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dynamicConfigPath = path.join(repoRoot, 'router-config.dynamic.json');
const dynamicConfigBackupPath = `${dynamicConfigPath}.regression-test-bak`;
const scanCachePath = path.join(repoRoot, '.cache', 'scan-cache.json');
const scanCacheBackupPath = `${scanCachePath}.regression-test-bak`;

async function drainStream(stream: AsyncIterable<AssistantMessageEvent>) {
  const events: AssistantMessageEvent[] = [];
  for await (const ev of stream) events.push(ev);
  return events;
}

describe('Sticky model regression (driveStream must never call pi.setModel)', () => {
  let mod: typeof import('../index.ts');
  let defaultExport: any;
  let tmpDir: string;
  let cwdSpy: ReturnType<typeof vi.spyOn>;
  let hadDyn: boolean;
  let hadCache: boolean;

  beforeEach(async () => {
    // Held until afterEach restores both shared files — see
    // router-state-lock.ts for why this must span the whole test.
    await acquireRouterStateLock();

    hadDyn = fs.existsSync(dynamicConfigPath);
    if (hadDyn) fs.renameSync(dynamicConfigPath, dynamicConfigBackupPath);
    hadCache = fs.existsSync(scanCachePath);
    if (hadCache) fs.renameSync(scanCachePath, scanCacheBackupPath);

    // Write a minimal "fresh, already-scraped" scan-cache so the unawaited
    // session_start scan() is a no-op (see writeNoOpScanCache docs). Without
    // this, scan() ends by swapping cfg/router to a dynamic config that
    // races this test's groupStream() call — the root cause of the CI-only
    // "No available models for group 'standard'" flake.
    writeNoOpScanCache(scanCachePath);

    // Isolated project config: keep the real "standard" group's method/
    // min_gdpval (so this remains a faithful regression test of real routing
    // behaviour) but clear fallback_groups so a resolution failure can't
    // cascade into other groups whose candidate pools depend on machine-local
    // state this test doesn't control.
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'router-sticky-model-'));
    fs.mkdirSync(path.join(tmpDir, '.pi'), { recursive: true });
    fs.writeFileSync(
      path.join(tmpDir, '.pi', 'router-config.json'),
      JSON.stringify({ model_groups: { standard: { fallback_groups: [], min_gdpval: 0 } } })
    );
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(tmpDir);

    vi.resetModules();
    mod = await import('../index.ts');
    defaultExport = mod.default;
  });

  afterEach(() => {
    cwdSpy.mockRestore();
    fs.rmSync(tmpDir, { recursive: true, force: true });
    // Remove the no-op scan-cache (hadCache reflects the ORIGINAL file,
    // restored below if it existed).
    removeNoOpScanCache(scanCachePath);
    if (hadDyn) fs.renameSync(dynamicConfigBackupPath, dynamicConfigPath);
    if (hadCache) fs.renameSync(scanCacheBackupPath, scanCachePath);
    releaseRouterStateLock();
  });

  it('routes to a different candidate on each call without ever swapping the session model', async () => {
    const onHandlers: Record<string, (ev: any, ctx: any) => any> = {};
    const setModel = vi.fn(async () => true);

    const pi: any = {
      registerTool: vi.fn(),
      registerCommand: vi.fn(),
      registerProvider: vi.fn(),
      setModel,
      on: vi.fn((event: string, handler: any) => {
        onHandlers[event] = handler;
      }),
    };

    defaultExport(pi);

    // Two fake "real" candidate models on providers the router does not
    // manage itself (not in PROVIDER_MAP), so no apiKey is required — mirrors
    // how an extension-registered provider (e.g. claude-bridge) looks to the
    // router. Both use gdpval-mapped ids so the "standard" group's
    // min_gdpval threshold accepts them.
    const fakeModels: Record<string, any> = {
      'fake-provider-a/claude-sonnet-4-6': {
        provider: 'fake-provider-a',
        id: 'claude-sonnet-4-6',
        api: 'fake-api',
      },
      'fake-provider-b/claude-opus-4-6': {
        provider: 'fake-provider-b',
        id: 'claude-opus-4-6',
        api: 'fake-api',
      },
    };

    function makeStream(providerId: string) {
      return (async function* () {
        yield { type: 'text_delta', text: `hi from ${providerId}` };
        yield { type: 'done' };
      })();
    }

    const modelRegistry = {
      getAvailable: () => Object.values(fakeModels),
      find: (provider: string, id: string) => fakeModels[`${provider}/${id}`] ?? null,
      getApiKeyForProvider: async () => null,
      runtime: {
        streamSimple: (model: any) => makeStream(model.provider),
      },
    };

    const ctx: any = {
      modelRegistry,
      cwd: tmpDir,
      ui: { setFooter: vi.fn() },
    };
    await onHandlers['session_start']?.({}, ctx);

    const groupModel = { provider: 'standard', id: 'standard' };
    const context: any = { messages: [{ role: 'user', content: 'hello' }] };

    for (let turn = 0; turn < 2; turn++) {
      const stream = defaultExport.groupStream(groupModel, context, {});
      const events = await drainStream(stream);
      const textEvents = events.filter((e: any) => e.type === 'text_delta');
      expect(textEvents.length).toBeGreaterThan(0);
    }

    // The router must never mutate the session's active model — that is
    // exactly the bug that made group routing stop working after turn 1.
    expect(setModel).not.toHaveBeenCalled();
  });
});
